name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: build
      run: |
          chmod +x ./build.sh
          ./build.sh
    - name: build_faster
      run: |
          chmod +x ./build_faster.sh
          ./build_faster.sh
