name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1

    - name: set up TF
      run: cd ${{ github.workspace }}

    - name: build
      run: |
          chmod -x ./build.sh
          sh ./build.sh
    - name: build_faster
      run: |
          chmod -x ./build_faster.sh
          sh ./build_faster.sh
