name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2

    - name: set up TF
      run: |
          cd ${GITHUB_WORKSPACE}
          echo ${GITHUB_WORKSPACE}
    - name: build
      run: |
          sh ${GITHUB_WORKSPACE}/build.sh
    - name: build_faster
      run: |
          sh ${GITHUB_WORKSPACE}/build_faster.sh
